[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
contract = "9Nu9W9e6D7fKP7omiWw8Z14J1NnWpVjqWp7FwJ7J7wCQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
